synth_adder:
	vivado -mode batch -source synth_adder.tcl -log synth_adder.log -nojournal -notrace

implement_adder:
	vivado -mode batch -source implement_adder.tcl -log implement_adder.log -nojournal -notrace

clean:
	rm -f *.bit *.jou *.txt *.pb *.wdb
	rm -Rf */.dir


