about:
	cat aboutme.txt
reverse:
	rev aboutme.txt > reverse.txt
upper:
	sed -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/' aboutme.txt > upper.txt
lineno:
	nl aboutme.txt > lineno.txt
bottom:
	tail -n 3 aboutme.txt > bottom.txt
clean:
	rm -f reverse.txt upper.txt lineno.txt bottom.txt


