test_cnt1:
	xvlog cnt1.sv tb_cnt.sv -sv --nolog
	xelab tb_cnt -debug typical --nolog
	xsim tb_cnt --nolog --runall

test_cnt2:
	xvlog cnt2.sv tb_cnt.sv -sv --nolog
	xelab tb_cnt -debug typical --nolog
	xsim tb_cnt --nolog --runall

test_cnt3:
	xvlog cnt3.sv tb_cnt.sv -sv --nolog
	xelab tb_cnt -debug typical --nolog
	xsim tb_cnt --nolog --runall

test_cnt4:
	xvlog cnt4.sv tb_cnt.sv -sv --nolog
	xelab tb_cnt -debug typical --nolog
	xsim tb_cnt --nolog --runall

test_cnt5:
	xvlog cnt5.sv tb_cnt.sv -sv --nolog
	xelab tb_cnt -debug typical --nolog
	xsim tb_cnt --nolog --runall

clean:
	rm -f *.jou *.log *.wdb *.pb